In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
load_path = 'data/processed/audio_call_matrix.csv'
audio = pd.read_csv(load_path)
print(audio.shape)
audio.head()

(3443, 206)

,instance_id,ticker,call_date,mean_Mean pitch,mean_Standard deviation,mean_Minimum pitch,mean_Maximum pitch,mean_Mean intensity,mean_Minimum intensity,mean_Maximum intensity,...,slope_Shimmer local,slope_Shimmer local dB,slope_Shimmer apq3,slope_Shimmer apq5,slope_Shimmer apq11,slope_Shimmer dda,slope_Mean autocorrelation,slope_Mean NHR,slope_Mean HNR,slope_Audio Length
0,20150225_LMAT,LMAT,2015-02-25,128.306624,62.107333,85.507267,459.584076,50.509184,68.939125,20.747126,...,-2.330198,-0.132341,-1.305716,-1.062710,-0.066187,-3.917266,0.047600,-0.089319,1.551691,0.539950
1,20150226_ACIW,ACIW,2015-02-26,180.028782,86.252295,85.077513,469.965090,55.346909,76.872280,30.401423,...,-3.407318,-0.286175,-1.736174,-1.860018,-1.867566,-5.208951,0.056797,-0.097081,2.265290,1.762820
2,20150226_ADSK,ADSK,2015-02-26,149.335950,43.851317,96.058017,366.591867,54.678148,71.869477,23.883329,...,-5.493085,-0.404579,-1.801149,-1.450769,-3.870413,-5.403370,-0.057257,-0.162725,0.784716,-1.591003
3,20150226_AMWD,AMWD,2015-02-26,126.843933,68.476689,86.869222,459.917133,49.005347,69.939225,17.778132,...,-2.441777,-0.147170,-1.765048,-2.220593,0.022430,-5.295544,0.058308,-0.112731,1.714723,-0.104369
4,20150226_ANSS,ANSS,2015-02-26,167.354891,73.969350,90.991058,524.365723,56.302637,71.844446,11.483946,...,-1.745179,-0.110823,-0.319652,-0.965877,-2.629804,-0.959063,-0.038944,0.080924,-0.993872,0.217071

In [3]:
load_path = 'data/processed/text_call_matrix.csv'
text = pd.read_csv(load_path)
print(text.shape)
text.head()

(3443, 2691)

,instance_id,ticker,call_date,mean_e0,mean_e1,mean_e2,mean_e3,mean_e4,mean_e5,mean_e6,...,slope_e374,slope_e375,slope_e376,slope_e377,slope_e378,slope_e379,slope_e380,slope_e381,slope_e382,slope_e383
0,20150225_LMAT,LMAT,2015-02-25,0.007288,0.000998,0.003222,-0.008416,-0.002437,-0.003212,-0.021679,...,0.028887,-0.020466,0.008103,0.015459,-0.024659,0.012380,0.016544,-0.027073,-0.007075,-0.015799
1,20150226_ACIW,ACIW,2015-02-26,-0.010614,-0.003885,0.005300,-0.021778,0.003938,-0.011949,-0.017517,...,-0.019642,-0.003559,0.026505,0.018677,0.009102,0.039975,0.032946,0.048909,0.066477,-0.001588
2,20150226_ADSK,ADSK,2015-02-26,-0.024106,-0.013536,0.010253,-0.009161,0.025073,0.000895,-0.002943,...,-0.036131,0.009026,0.070006,-0.017932,0.051465,0.013141,-0.011438,0.019301,-0.018877,0.004766
3,20150226_AMWD,AMWD,2015-02-26,0.004546,-0.019589,0.013683,0.013155,0.024236,0.005180,-0.040526,...,-0.021931,-0.002852,0.003339,0.021923,0.024523,-0.006380,0.027933,-0.019496,-0.004593,0.000105
4,20150226_ANSS,ANSS,2015-02-26,-0.006074,-0.020038,0.010920,-0.017417,0.007784,-0.002698,-0.031453,...,-0.009045,0.004114,-0.030518,0.000137,0.008410,0.000306,-0.000478,-0.021842,0.032748,-0.001392

In [10]:
X_all = pd.concat([text,audio],axis=1)
X_all.head()

,instance_id,ticker,call_date,mean_e0,mean_e1,mean_e2,mean_e3,mean_e4,mean_e5,mean_e6,...,slope_Shimmer local,slope_Shimmer local dB,slope_Shimmer apq3,slope_Shimmer apq5,slope_Shimmer apq11,slope_Shimmer dda,slope_Mean autocorrelation,slope_Mean NHR,slope_Mean HNR,slope_Audio Length
0,20150225_LMAT,LMAT,2015-02-25,0.007288,0.000998,0.003222,-0.008416,-0.002437,-0.003212,-0.021679,...,-2.330198,-0.132341,-1.305716,-1.062710,-0.066187,-3.917266,0.047600,-0.089319,1.551691,0.539950
1,20150226_ACIW,ACIW,2015-02-26,-0.010614,-0.003885,0.005300,-0.021778,0.003938,-0.011949,-0.017517,...,-3.407318,-0.286175,-1.736174,-1.860018,-1.867566,-5.208951,0.056797,-0.097081,2.265290,1.762820
2,20150226_ADSK,ADSK,2015-02-26,-0.024106,-0.013536,0.010253,-0.009161,0.025073,0.000895,-0.002943,...,-5.493085,-0.404579,-1.801149,-1.450769,-3.870413,-5.403370,-0.057257,-0.162725,0.784716,-1.591003
3,20150226_AMWD,AMWD,2015-02-26,0.004546,-0.019589,0.013683,0.013155,0.024236,0.005180,-0.040526,...,-2.441777,-0.147170,-1.765048,-2.220593,0.022430,-5.295544,0.058308,-0.112731,1.714723,-0.104369
4,20150226_ANSS,ANSS,2015-02-26,-0.006074,-0.020038,0.010920,-0.017417,0.007784,-0.002698,-0.031453,...,-1.745179,-0.110823,-0.319652,-0.965877,-2.629804,-0.959063,-0.038944,0.080924,-0.993872,0.217071

In [13]:
X_unscaled = X_all.select_dtypes(include="number") # only include numerical data
X_unscaled.head()

,mean_e0,mean_e1,mean_e2,mean_e3,mean_e4,mean_e5,mean_e6,mean_e7,mean_e8,mean_e9,...,slope_Shimmer local,slope_Shimmer local dB,slope_Shimmer apq3,slope_Shimmer apq5,slope_Shimmer apq11,slope_Shimmer dda,slope_Mean autocorrelation,slope_Mean NHR,slope_Mean HNR,slope_Audio Length
0,0.007288,0.000998,0.003222,-0.008416,-0.002437,-0.003212,-0.021679,0.001413,0.007203,-0.012453,...,-2.330198,-0.132341,-1.305716,-1.062710,-0.066187,-3.917266,0.047600,-0.089319,1.551691,0.539950
1,-0.010614,-0.003885,0.005300,-0.021778,0.003938,-0.011949,-0.017517,-0.006753,0.007547,-0.005920,...,-3.407318,-0.286175,-1.736174,-1.860018,-1.867566,-5.208951,0.056797,-0.097081,2.265290,1.762820
2,-0.024106,-0.013536,0.010253,-0.009161,0.025073,0.000895,-0.002943,-0.017159,-0.014945,-0.022568,...,-5.493085,-0.404579,-1.801149,-1.450769,-3.870413,-5.403370,-0.057257,-0.162725,0.784716,-1.591003
3,0.004546,-0.019589,0.013683,0.013155,0.024236,0.005180,-0.040526,-0.003097,-0.007633,-0.020502,...,-2.441777,-0.147170,-1.765048,-2.220593,0.022430,-5.295544,0.058308,-0.112731,1.714723,-0.104369
4,-0.006074,-0.020038,0.010920,-0.017417,0.007784,-0.002698,-0.031453,-0.002611,0.001809,-0.010350,...,-1.745179,-0.110823,-0.319652,-0.965877,-2.629804,-0.959063,-0.038944,0.080924,-0.993872,0.217071

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_unscaled)
X = pd.DataFrame(scaler.transform(X_unscaled))
X.head()

,0,1,2,3,4,5,6,7,8,9,...,2881,2882,2883,2884,2885,2886,2887,2888,2889,2890
0,0.753981,0.993403,-0.419176,-0.118176,-1.287133,-0.406465,-0.109397,0.317065,0.763479,-0.166187,...,-0.652649,-0.404604,-0.796379,-0.288610,0.250784,-0.796410,0.827001,-1.062459,1.114485,0.612622
1,-0.368756,0.599732,-0.228464,-1.106929,-0.711779,-1.313041,0.186642,-0.280573,0.792244,0.432471,...,-1.102121,-1.225531,-1.131822,-0.682565,-0.222323,-1.131935,0.946281,-1.156935,1.588165,0.923432
2,-1.214970,-0.178344,0.226308,-0.173269,1.195729,0.019666,1.223266,-1.042183,-1.087803,-1.093151,...,-1.972492,-1.857384,-1.182455,-0.480353,-0.748344,-1.182437,-0.532948,-1.955954,0.605375,0.071011
3,0.582011,-0.666396,0.541185,1.477994,1.120127,0.464358,-1.450015,-0.013000,-0.476615,-0.903808,...,-0.699210,-0.483738,-1.154322,-0.860728,0.274059,-1.154428,0.965881,-1.347425,1.222704,0.448860
4,-0.084050,-0.702603,0.287592,-0.784225,-0.364707,-0.353111,-0.804656,0.022536,0.312563,0.026546,...,-0.408527,-0.289773,-0.027969,-0.240764,-0.422515,-0.027995,-0.295428,1.009736,-0.575233,0.530558

In [18]:
y = pd.read_csv('data/y.csv')
y = y.drop(columns=["Unnamed: 0"])
y.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
y_1d = y.sum(axis=1)
type(y_1d)

pandas.Series